### ISSUE TITLE
Error al mostrar variables de laravel en vuepress

### ISSUE THREAD

**Issue by EdixonAlberto** [StydeNet/laravel-spanish-docs#268]
Al parecer las variables usadas en laravel: {{ $foo }} si no se encierran en bloques de código, no se muestran en pantalla. Debe ser porque entra en conflicto con la sintaxis de vuepress 🤷‍♂️. Alguna solución?

![Image 028](https://user-images.githubusercontent.com/40126214/59958863-4ae63580-947b-11e9-95a1-4bb3c0a17a9a.jpg)

**Comment by dvalpx** [comment]
Hola Edixon, gracias por informar. Voy a revisar y buscar una solución al problema.

**Comment by dvalpx** [comment]
El problema fue solucionado en la página en cuestión. Estoy comenzando a agregar cambios para el resto de las páginas.
