### ISSUE TITLE
Enlace no funciona en el archivo docs/authorization.md

### ISSUE THREAD

**Issue by asilvabe** [StydeNet/laravel-spanish-docs#270]
Inicialmente pensé que se trataba de un texto que estaba de más. Pero al intentar hacer el pull request me di cuenta de que se trata de un enlace.

El punto es que desde la URL principal del proyecto el siguiente enlace no funciona. Sólo funciona cuando se consulta la página desde GitHub.

Es en el segundo párrafo luego del título **Creando políticas -> Generando políticas**, la cadena _"artisan command"_: 

> Puedes generar una política usando el comando make:policy **artisan command**

**Comment by dvalpx** [comment]
Hola @asilvabe gracias por la información 👍 

Te referías al texto del enlace _artisan command_? Si era eso, lo acabo de arreglar, pero no estoy 100% seguro si ese era el fallo que estabas reportando porque el enlace si funciona como tal.

De nuevo, gracias por el reporte. Si ese no era el fallo por favor no dudes en hacermelo saber :-)

**Comment by asilvabe** [comment]
Sí, ese era el enlace 😀
Funciona perfecto 💪
