### ISSUE TITLE
Falta sección: Eloquent ORM - API Resources

### ISSUE THREAD

**Issue by ameppema** [StydeNet/laravel-spanish-docs#276]
@dvalpx Buenas, revisando su excelente documentación he podido darme cuenta de que falta la traducción de la sección **Eloquent ORM - API Resources**, no se si era algo que no estaba incluido en vuestros planes traducir o simplemente es algo que se olvido hacer, de ser así, dejo este ISSUE abierto por si os animáis a hacerlo, mil gracias por todo el esfuerzo, un abrazo.

**Comment by dvalpx** [comment]
Hola @ameppema gracias por la información, ya verifico y lo soluciono a la brevedad posible.

**Comment by dvalpx** [comment]
Issue corregido @ameppema, el archivo estaba totalmente traducido pero no se había agregado al menú lateral CC @sileence

**Comment by ameppema** [comment]
Muchas, muchas gracias, sois espectaculares **@sileence @dvalpx**, un fuerte abrazo
