### ISSUE TITLE
Pequeña errata de texto!

### ISSUE THREAD

**Issue by ameppema** [StydeNet/laravel-spanish-docs#277]
Buenas tardes! @sileence @dvalpx

Estaba repasando la documentación y me he podido dar cuenta de una pequeño error de texto que es el siguiente:

*Con error* - Después de haber instalado Laravel, necesitarás **congigurar**
*Sin error* - Después de haber instalado Laravel, necesitarás **configurar**

Envío el enlace: [https://documentacion-laravel.com/installation.html#permisos-para-directorios](url)

Saludos.

**Comment by dvalpx** [comment]
Hola @ameppema muchas gracias, lo acabo de corregir :-)

**Comment by ameppema** [comment]
Muchas gracias, saludos.
