### ISSUE TITLE
Revertir vs Reversar

### ISSUE THREAD

**Issue by ameppema** [StydeNet/laravel-spanish-docs#278]
Buenas tardes **@sileence** **@dvalpx**, estaba leyendo vuestra excelente documentación de Laravel 5.8 y en la sección de **Base de datos: Migraciones** utilizáis un verbo que me causo confusión; como sé que nuestro idioma es muy variado y que existen multiples regiones en el mundo donde se habla de forma diferente, consulte con la RAE para entender mejor el significado del verbo, resultando que la acepción de dicho verbo no es la más adecuada al tema referido ([consulta RAE](https://dle.rae.es/?id=WO3rQ47)), por lo que quería sugerir cambiar el verbo **"reversar" por "revertir"** creo que se entendería mejor al ser un verbo más conocido y que ya utilizáis en esa misma página, a continuación dejo el enlace por si creéis que es buena idea cambiarlo:

[https://documentacion-laravel.com/migrations.html#introduccion](url)

Muchas gracias por vuestro gran trabajo y saludos.

Paul.

**Comment by sileence** [comment]
Estoy de acuerdo, deberíamos usar revertir.
