### ISSUE TITLE
Help us update "eloquent-relationships.md"

### ISSUE THREAD

**Issue by dvalpx** [StydeNet/laravel-spanish-docs#300]
Commits missing:

- https://github.com/laravel/docs/commit/b9f6443acd4f0912e8a6502f8b849cb989f34b5c#diff-8ee0e91f55a653895f3d8dc328c2cfc4
- https://github.com/laravel/docs/commit/07886baa8e68e0c014047dc3d5dcb11ddd553219#diff-8ee0e91f55a653895f3d8dc328c2cfc4
- https://github.com/laravel/docs/commit/6ea5c2b96f6ada4bf2823f4d16c126a1bbbf1657#diff-8ee0e91f55a653895f3d8dc328c2cfc4
- https://github.com/laravel/docs/commit/83890648bc5b55428132fb18400f75674a593731#diff-8ee0e91f55a653895f3d8dc328c2cfc4

**Comment by reysmerwvr** [comment]
Working on this
