### ISSUE TITLE
Help us update "errors.md"

### ISSUE THREAD

**Issue by dvalpx** [StydeNet/laravel-spanish-docs#303]
Commits missing:

- https://github.com/laravel/docs/commit/78ce03eb140c838482175eb06bccc92c4d2d52ad#diff-8f8a0b09fa5f199438dd9e7557ce36db
- https://github.com/laravel/docs/commit/861a15a58db44cda432d3c6a357fc5304c9418c0#diff-8f8a0b09fa5f199438dd9e7557ce36db

**Comment by Saimon-git** [comment]
working on
