### ISSUE TITLE
Help us update "horizon.md"

### ISSUE THREAD

**Issue by dvalpx** [StydeNet/laravel-spanish-docs#305]
Commits missing:

- https://github.com/laravel/docs/commit/1b5d0e0e44128f0cb6210b4f481a603874dd852a#diff-e480d6c3e875ccf4480939a7a7f7071b
- https://github.com/laravel/docs/commit/7dc5fe9b7520c5baa8fd52638e4f389d0fe39d8b#diff-e480d6c3e875ccf4480939a7a7f7071b

**Comment by Saimon-git** [comment]
working on
