### ISSUE TITLE
Help us update "migrations.md"

### ISSUE THREAD

**Issue by dvalpx** [StydeNet/laravel-spanish-docs#307]
Commits missing:

- https://github.com/laravel/docs/commit/1b5d0e0e44128f0cb6210b4f481a603874dd852a#diff-728f15ac22c45288eb73bb06e71ed5b4
- https://github.com/laravel/docs/commit/66ce4fd3ab8b97540127bb171c7dc87240031a82#diff-728f15ac22c45288eb73bb06e71ed5b4
- https://github.com/laravel/docs/commit/79475a958f2c76439412fabf434213dd488f4e82#diff-728f15ac22c45288eb73bb06e71ed5b4
- https://github.com/laravel/docs/commit/1fc0c3ab97b00969ebb50fb04c86b95d0c1d0a0f#diff-728f15ac22c45288eb73bb06e71ed5b4

**Comment by Saimon-git** [comment]
I am working in this issue
