### ISSUE TITLE
Help us update "mocking.md"

### ISSUE THREAD

**Issue by dvalpx** [StydeNet/laravel-spanish-docs#308]
Commits missing:

- https://github.com/laravel/docs/commit/1b5d0e0e44128f0cb6210b4f481a603874dd852a#diff-6adab0aea8d7bde66498f8c1928022d3
- https://github.com/laravel/docs/commit/0d299ddf249c43e33c54e0245af4ca17d1f8b579#diff-6adab0aea8d7bde66498f8c1928022d3
- https://github.com/laravel/docs/commit/f4b3922b0edbfb111d9597f301703fef13f07132#diff-6adab0aea8d7bde66498f8c1928022d3

**Comment by Saimon-git** [comment]
working on
