### ISSUE TITLE
Help us update "notifications.md"

### ISSUE THREAD

**Issue by dvalpx** [StydeNet/laravel-spanish-docs#325]
Commits missing:

- https://github.com/laravel/docs/commit/1b5d0e0e44128f0cb6210b4f481a603874dd852a#diff-7c04c1591e2821d381785df56ebd70af
- https://github.com/laravel/docs/commit/c7913006a3af5e95bb4b7356d6cbab2d391f6dc8#diff-7c04c1591e2821d381785df56ebd70af
- https://github.com/laravel/docs/commit/3d1cf7d5d58d77ebf5d9a53e74aad9bec14bc6cb#diff-7c04c1591e2821d381785df56ebd70af
- https://github.com/laravel/docs/commit/2a6b0b9129164394dab2c62bda674158323d0981#diff-7c04c1591e2821d381785df56ebd70af
- https://github.com/laravel/docs/commit/4836dd8f55bf5dc8d8bbd1886d639b22760b4b8e#diff-7c04c1591e2821d381785df56ebd70af
- https://github.com/laravel/docs/commit/c1de43c5977ef2f6d54e55a77b1a0578ac45f94a#diff-7c04c1591e2821d381785df56ebd70af
- https://github.com/laravel/docs/commit/3f5e129bcacbde9b392216c05cde70d91479c92d#diff-7c04c1591e2821d381785df56ebd70af

**Comment by callmeanto** [comment]
I'll work on this one!
