### ISSUE TITLE
Help us update "pagination.md"

### ISSUE THREAD

**Issue by dvalpx** [StydeNet/laravel-spanish-docs#326]
Commits missing:

- https://github.com/laravel/docs/commit/1b5d0e0e44128f0cb6210b4f481a603874dd852a#diff-8933c44b45493d40d2007cdf0ce43109
- https://github.com/laravel/docs/commit/091747ff71fc948eea8749b5521957ce56173fea#diff-8933c44b45493d40d2007cdf0ce43109

**Comment by callmeanto** [comment]
I'll work on this! :)

**Comment by callmeanto** [comment]
Ready!
