### ISSUE TITLE
Help us update "passport.md"

### ISSUE THREAD

**Issue by dvalpx** [StydeNet/laravel-spanish-docs#327]
Commits missing:

- https://github.com/laravel/docs/commit/1b5d0e0e44128f0cb6210b4f481a603874dd852a#diff-36a612d0cef3c19535a8aa89276ea49e
- https://github.com/laravel/docs/commit/0679645b17b9a9d004167dcfc4a7f822f92b7fbc#diff-36a612d0cef3c19535a8aa89276ea49e

**Comment by reysmerwvr** [comment]
Working on this
