### ISSUE TITLE
Help us update "queries.md"

### ISSUE THREAD

**Issue by dvalpx** [StydeNet/laravel-spanish-docs#330]
Commits missing:

- https://github.com/laravel/docs/commit/1b5d0e0e44128f0cb6210b4f481a603874dd852a#diff-67c26103052dd14579b331a21ad89e3e
- https://github.com/laravel/docs/commit/2de42e387dc8637c9a4d53e9895af7e16d247ba6#diff-67c26103052dd14579b331a21ad89e3e

**Comment by reysmerwvr** [comment]
Working on this
