### ISSUE TITLE
Help us update "queues.md"

### ISSUE THREAD

**Issue by dvalpx** [StydeNet/laravel-spanish-docs#331]
Missing commits:

- https://github.com/laravel/docs/commit/1b5d0e0e44128f0cb6210b4f481a603874dd852a#diff-c396df05e5560db37f42604722a474c7
- https://github.com/laravel/docs/commit/739f3deb549fe368182ef322a30cd0e04aea8564#diff-c396df05e5560db37f42604722a474c7
- https://github.com/laravel/docs/commit/ac8b01ae1d190fa3ca52921444ecd9a3f06ebb55#diff-c396df05e5560db37f42604722a474c7
- https://github.com/laravel/docs/commit/e4d329ca9b8911b79207e26b97128c19fa952839#diff-c396df05e5560db37f42604722a474c7

**Comment by dimitriacosta** [comment]
I'm taking this one
