### ISSUE TITLE
Help us update "redis.md"

### ISSUE THREAD

**Issue by dvalpx** [StydeNet/laravel-spanish-docs#332]
Commits missing:

- https://github.com/laravel/docs/commit/9caa5b863eda5fb45313967b4aa1d082293e1d2c#diff-aac08daf8601d2cee3108414db3a5691
- https://github.com/laravel/docs/commit/b2231f993ff39d26ea78ac427a2ebbef0b109da5#diff-aac08daf8601d2cee3108414db3a5691
- https://github.com/laravel/docs/commit/2b744911844cb0b05e6391b3f0c27f666aae8a2e#diff-aac08daf8601d2cee3108414db3a5691
- https://github.com/laravel/docs/commit/5da9911f199c5ddd7d2a292e8fc63ccfcebff076#diff-aac08daf8601d2cee3108414db3a5691
- https://github.com/laravel/docs/commit/67dd12fd081c0346978e18ab2380ade0a1df379d#diff-aac08daf8601d2cee3108414db3a5691
- https://github.com/laravel/docs/commit/bf4d1937ccec499da30ce3d4042b7551037a40a5#diff-aac08daf8601d2cee3108414db3a5691
- https://github.com/laravel/docs/commit/beb24990a95ec480a8265c0510d06728b7880276#diff-aac08daf8601d2cee3108414db3a5691
- https://github.com/laravel/docs/commit/2dca6cc722add5c542029b8db0e4f8e460af34c5#diff-aac08daf8601d2cee3108414db3a5691

**Comment by espipj** [comment]
Hello @dvalpx can I have this assigned to me. I can work on it during the weekend 😊

**Comment by dvalpx** [comment]
@espipj Sure :+1:
