### ISSUE TITLE
Help us update "requests.md"

### ISSUE THREAD

**Issue by dvalpx** [StydeNet/laravel-spanish-docs#333]
Commits missing:

- https://github.com/laravel/docs/commit/92be863c5a1d33c21c01bacdc13419a36c79cba5#diff-37761f46d18f7235fb5e44a287e8ecc2
- https://github.com/laravel/docs/commit/2e2875dd895a5fd9370d459f810d64cc6eb12a9c#diff-37761f46d18f7235fb5e44a287e8ecc2

**Comment by reysmerwvr** [comment]
Working on this
