### ISSUE TITLE
Help us update "seeding.md"

### ISSUE THREAD

**Issue by dvalpx** [StydeNet/laravel-spanish-docs#334]
Commits missing:

- https://github.com/laravel/docs/commit/1b5d0e0e44128f0cb6210b4f481a603874dd852a#diff-9dd70ec85b4e56d2764e60132dfd9025
- https://github.com/laravel/docs/commit/537c4dd17499b4c353a9a188231c5cfd2f0b0929#diff-9dd70ec85b4e56d2764e60132dfd9025

**Comment by reysmerwvr** [comment]
Working on this
