### ISSUE TITLE
Help us update "releases.md"

### ISSUE THREAD

**Issue by dvalpx** [StydeNet/laravel-spanish-docs#335]
Commits missing:

- https://github.com/laravel/docs/commit/3b69467d7e8d7be84f5b956605c89027db88efb9#diff-7a71f7126aa9b19a55f3436076d86c89
- https://github.com/laravel/docs/commit/8baa467d25b82790dcdfb5718a9a50a688b75e40#diff-7a71f7126aa9b19a55f3436076d86c89
- https://github.com/laravel/docs/commit/28dc6e672c2802ccf42ca5d1e3c7b913c04a0371#diff-7a71f7126aa9b19a55f3436076d86c89
- https://github.com/laravel/docs/commit/5785a472304309dfb7fe8bf6978852ef36c2bc65#diff-7a71f7126aa9b19a55f3436076d86c89
- https://github.com/laravel/docs/commit/fb0d522bcdc12b44520765e20c5b66de66855ffd#diff-7a71f7126aa9b19a55f3436076d86c89
- https://github.com/laravel/docs/commit/8a4e2ea6a3b7b2a8d9574d8ec7efc5855d41f43e#diff-7a71f7126aa9b19a55f3436076d86c89
- https://github.com/laravel/docs/commit/0b50627f3e503a257e9291485db768ddad1ce729#diff-7a71f7126aa9b19a55f3436076d86c89

**Comment by ArielSalvadorDev** [comment]
I want to work on this
