### ISSUE TITLE
Help us update "scheduling.md"

### ISSUE THREAD

**Issue by dvalpx** [StydeNet/laravel-spanish-docs#349]
Missing commits:

- https://github.com/laravel/docs/commit/b42878c36ab82cbe4feab1e11a4e16dad7242c5d#diff-022a5576680c74fd027641aee6e00e6d
- https://github.com/laravel/docs/commit/1b5d0e0e44128f0cb6210b4f481a603874dd852a#diff-022a5576680c74fd027641aee6e00e6d

**Comment by rivermartinez** [comment]
Working on this

**Comment by RiverMartinezG** [comment]
#365
