### ISSUE TITLE
Help us update "scout.md"

### ISSUE THREAD

**Issue by dvalpx** [StydeNet/laravel-spanish-docs#350]
Missing commits:

- https://github.com/laravel/docs/commit/1b5d0e0e44128f0cb6210b4f481a603874dd852a#diff-037bd9891308294d237abd7d68803850
- https://github.com/laravel/docs/commit/5f4e1be10da6b90e482089741bd432088dccd4db#diff-037bd9891308294d237abd7d68803850

**Comment by RiverMartinezG** [comment]
Working on this
