### ISSUE TITLE
Help us update "valet.md"

### ISSUE THREAD

**Issue by dvalpx** [StydeNet/laravel-spanish-docs#354]
Missing commits:

- https://github.com/laravel/docs/commit/923401086adca72669dadfb4a96ef612144b7ef5#diff-9067c7effdddeae94d45c503c1725e97
- https://github.com/laravel/docs/commit/f47d2f8878af5e5343748a775024a4031082c476#diff-9067c7effdddeae94d45c503c1725e97

**Comment by soberanes** [comment]
Working on this
