### ISSUE TITLE
Help us update "validation.md"

### ISSUE THREAD

**Issue by dvalpx** [StydeNet/laravel-spanish-docs#355]
Missing commits:

- https://github.com/laravel/docs/commit/9839758a6ec643ceb249934fa0b1eaf459db3a22#diff-eff160cdcda8f026fba936da7f3fea15
- https://github.com/laravel/docs/commit/54012d8b807575d5f6b767c0bfdc6a5a9bfbf3cd#diff-eff160cdcda8f026fba936da7f3fea15
- https://github.com/laravel/docs/commit/1b5d0e0e44128f0cb6210b4f481a603874dd852a#diff-eff160cdcda8f026fba936da7f3fea15
- https://github.com/laravel/docs/commit/f1c9907c5b5df8940bacf1b64daa105ffcbf0730#diff-eff160cdcda8f026fba936da7f3fea15
- https://github.com/laravel/docs/commit/ee4369817de503fd13e4b1091039dcf3ab5fc379#diff-eff160cdcda8f026fba936da7f3fea15
- https://github.com/laravel/docs/commit/97428f0f41a18604ccaba2920f23debf9df7df1a#diff-eff160cdcda8f026fba936da7f3fea15
- https://github.com/laravel/docs/commit/5f721672d1d8a18b97a2c1639d955e43ad14b0a4#diff-eff160cdcda8f026fba936da7f3fea15
- https://github.com/laravel/docs/commit/1631c465546af2606adbbc6c7928d59c5f3c6aeb#diff-eff160cdcda8f026fba936da7f3fea15
- https://github.com/laravel/docs/commit/759a2f14738e97d43bb8cc9009c336fa1b8ab4cb#diff-eff160cdcda8f026fba936da7f3fea15

**Comment by soberanes** [comment]
Working on this
