### ISSUE TITLE
Help us update "verification.md"

### ISSUE THREAD

**Issue by dvalpx** [StydeNet/laravel-spanish-docs#356]
Missing commits:

- https://github.com/laravel/docs/commit/6aa76234f4a8e87bd41cd6454be8440fba6b213d#diff-b63407feb73bdb3fbd702dafa4be77df
- https://github.com/laravel/docs/commit/5785a472304309dfb7fe8bf6978852ef36c2bc65#diff-b63407feb73bdb3fbd702dafa4be77df
- https://github.com/laravel/docs/commit/1b5d0e0e44128f0cb6210b4f481a603874dd852a#diff-b63407feb73bdb3fbd702dafa4be77df

**Comment by soberanes** [comment]
Working on this
